### ISSUE TITLE
New telegram game for cheat

### ISSUE THREAD

**Issue by mohammad213** [danog/TelegramCheats#19]
Please add below game in cheat list

"Paintio"

https://www.gamee.com/game-bot/paintio-57d7fd324d20dfd94025d5bfc70274ee32b79b0e#tgShareScoreUrl=tgb%3A%2F%2Fshare_game_score%3Fhash%3DxaDwwROiDMAiugIrzVHc

**Comment by danog** [comment]
sorri I don't provide support for this anymore
