### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by qualkuno** [danog/TelegramCheats#6]
Ciao, ho provato a usare il cheat con il gioco telegram "lumberjack" ma non funziona, come mai?

**Comment by veetaw** [comment]
@qualkuno al momento non funziona con i giochi di gamebot

**Comment by qualkuno** [comment]
Ah ok, grazie!

**Comment by veetaw** [comment]
@qualkuno

**Comment by danog** [comment]
Funziona in modo intermittente, purtroppo.

**Comment by veetaw** [comment]
rip

**Comment by danog** [comment]
@veetaw cos

**Comment by veetaw** [comment]
@danog much rip, so cos

**Comment by veetaw** [comment]
@veetaw qualcuno chiuda quesa pullreq prima che cada nel degrado

**Comment by danog** [comment]
@veetaw troppo tardi xd

**Comment by veetaw** [comment]
@danog cos

**Comment by Creeperiano99** [comment]
@veetaw 🤔

**Comment by AryToNeX** [comment]
@Creeperiano99 ANDIAMO A FUNGHI, È MEGLIO

**Comment by veetaw** [comment]
@AryToNeX MY LITTLE PORNY

**Comment by danog** [comment]
@veetaw NOH

**Comment by veetaw** [comment]
@danog COS

**Comment by qualkuno** [comment]
WTF!? lol

**Comment by AryToNeX** [comment]
@qualkuno Apokalysseeee

**Comment by veetaw** [comment]
@AryToNeX KIAO AGG

**Comment by AryToNeX** [comment]
CHIUDETE L'INTERNET ADESSO, QUI ARRIVIAMO AL DEGRADO

**Comment by qualkuno** [comment]
@AryToNeX Nooooooow

**Comment by danog** [comment]
@AryToNeX KE PEKKATO, GITHUB ERA L'UNICO POSTO SENZA DEGRADO CHE AVEVO :(

**Comment by veetaw** [comment]
AHHAAHAHAHAHHAHA

**Comment by AryToNeX** [comment]
@veetaw Se bestemmio su github vengo bannato? No vero?

**Comment by danog** [comment]
@AryToNeX ¯\_(ツ)_/¯

**Comment by veetaw** [comment]
@danog ¯\_(ツ)_/¯

**Comment by AryToNeX** [comment]
@danog *MARKDOWN* LOL

**Comment by danog** [comment]
fixed xd
