### ISSUE TITLE
dont work anymore

### ISSUE THREAD

**Issue by ArthurWinchest** [danog/TelegramCheats#9]

**Comment by veetaw** [comment]
@ArthurWinchest rip

**Comment by danog** [comment]
@ArthurWinchest Ikr xd

**Comment by AryToNeX** [comment]
@danog HAPPY LLAMA
SAD LLAMA
MENTALLY DISTURBED LLAMA
SUPER LLAMA
DRAMA LLAMA
BIG FAT MAMA LLAMA

**Comment by veetaw** [comment]
@AryToNeX KIAO AGG

**Comment by ArthurWinchest** [comment]
kkkkk

**Comment by Creeperiano99** [comment]
@ArthurWinchest 👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by danog** [comment]
@Creeperiano99 _____
< gud >
 -----
   \        \
    \        \
     \       _\^
      \    _- oo\
           \---- \______
                 \       )\
                ||-----||  \
                ||     ||

**Comment by veetaw** [comment]
@danog _____________________________
< hi, I am a broken ascii art >
 -----------------------------
         \
          \
            ^__^ 
    _______/(oo)
/\/(       /(__)
   | W----|| |~|
   ||     || |~|  ~~
             |~|  ~
             |_| o
             |#|/
            _+#+_

**Comment by danog** [comment]
Fixed xd
